version: 1

formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  app_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: C:\SheildX\logs\app\shieldx.log
    maxBytes: 5242880   # 5 MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: C:\SheildX\logs\app\errors.log
    maxBytes: 5242880
    backupCount: 5

  audit_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: C:\SheildX\logs\app\audit.log
    maxBytes: 5242880
    backupCount: 10

root:
  level: INFO
  handlers: [app_file, error_file]
